name: Deploy e OWASP

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'env-example.txt'
      - 'docker-compose.yml'
      - 'README.md'
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read
  security-events: write

concurrency:
  group: "pages"
  
jobs:
  precheck:
    name: 🔎 Precheck
    runs-on: ubuntu-latest
    steps:
      - name: Checar HTTPS online (HEAD)
        run: |
          set -e
          URL="https://www.momentodev.com"
          echo "Verificando $URL ..."
          # Aceita 200 ou redireção 301/302 (segue com -L)
          http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
             -L --retry 6 --retry-all-errors \
             --connect-timeout 5 --max-time 20 "$URL")
          echo "HTTP: $http_code"
          case "$http_code" in
            200|301|302) exit 0 ;;
            *) echo "Site fora do ar (HTTP $http_code)"; exit 1 ;;
          esac

  test-e2e:
    name: Teste E2E
    needs: [precheck]
    uses: ./.github/workflows/e2e.yml
    secrets: inherit
    with:
      branch: main

  security_final:
    name: 🔐 Security Suite
    needs: [test-e2e]
    if: success()
    uses: ./.github/workflows/security_final.yml
    secrets: inherit

  call-deploy:
    name: 🚀 Deploy Final
    needs: [security_final]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      branch: main